language: java
jdk:
  - oraclejdk8

branches:
  only:
  - master

before_install:
  # required libs for android build tools
  # sudo apt-get update
  # sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # newest Android NDK
  - wget http://dl.google.com/android/ndk/android-ndk-r10c-linux-x86_64.bin -O ndk.bin
  - chmod a+x ndk.bin
  - echo $PWD
  - $PWD/ndk.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10c
